import { useQuery } from '@tanstack/react-query'
import type { AxiosError } from 'axios'
import apiClient from '../client'
import {
  TBooks,
  TBooksResponse,
  TUseHomeQueryResult,
  TApiResponse,
} from '../type'

const fetchBooksData = async (): Promise<TBooks[]> => {
  const response = await apiClient.get<TBooksResponse>(
    '/api/admin/country-showcases',
  )
  return response?.data?.rows || []
}

export const booksApiMock: TBooksResponse = {
  status: true,
  message: '成功取得書本列表',
  rows: [
    {
      id: '68b05373564da72a7ab17536',
      bookImage: '/home/itinerary/hr-croatia/pattern.svg',
      landscapeImage: '/home/itinerary/hr-croatia/pattern.svg',
      title: '克羅埃西亞',
      subtitle: 'Republic Of Croatia',
      description: '克羅埃西亞位於歐洲東南部，深受中東及巴爾幹半島地區影響，從古羅馬遺跡如斯普利特的戴克里先宮，到中世紀的哥德式與文藝復興建築，處處可見歷史痕跡。',
      linkText: null,
      linkUrl: null,
      order: 1,
      createdAt: '2025-08-28T13:02:43.217Z',
      updatedAt: '2025-08-28T13:02:43.217Z',
      groupProducts: [],
      freeProducts: [],
      recoProducts: [],
    },
    {
      id: '68b05382564da72a7ab17537',
      bookImage: '/home/itinerary/cz-czech/pattern.svg',
      landscapeImage: '/home/itinerary/cz-czech/pattern.svg',
      title: '捷克',
      subtitle: 'Czech Republic',
      description: '捷克位於中歐心臟地帶，是個內陸國家，歷史上屬波西米亞王國，至今仍保有濃厚中世風情與歐陸歷史痕跡。',
      linkText: null,
      linkUrl: null,
      order: 2,
      createdAt: '2025-08-28T13:02:58.975Z',
      updatedAt: '2025-08-28T13:02:58.975Z',
      groupProducts: [],
      freeProducts: [],
      recoProducts: [],
    },
    {
      id: '68b05391564da72a7ab17538',
      bookImage: '/home/itinerary/pt-portugal/pattern.svg',
      landscapeImage: '/home/itinerary/pt-portugal/pattern.svg',
      title: '葡萄牙',
      subtitle: 'Portugal',
      description: '葡萄牙位在歐洲西南角，正面對著浩瀚大西洋，是地中海邊最璀璨的明珠，也是「航海時代的起點」。',
      linkText: null,
      linkUrl: null,
      order: 3,
      createdAt: '2025-08-28T13:03:13.127Z',
      updatedAt: '2025-08-28T13:03:13.127Z',
      groupProducts: [],
      freeProducts: [],
      recoProducts: [],
    },
    {
      id: '68b0539e564da72a7ab17539',
      bookImage: '/home/itinerary/ch-switzerland/pattern.svg',
      landscapeImage: '/home/itinerary/ch-switzerland/pattern.svg',
      title: '瑞士',
      subtitle: 'Switzerland',
      description: '瑞士位在中歐核心，阿爾卑斯山橫跨國土，是歐洲經典山水國度，也是高山鐵道及自然景觀的天堂。',
      linkText: null,
      linkUrl: null,
      order: 4,
      createdAt: '2025-08-28T13:03:26.187Z',
      updatedAt: '2025-08-28T13:03:26.187Z',
      groupProducts: [],
      freeProducts: [],
      recoProducts: [],
    },
    {
      id: '68b053ad564da72a7ab1753a',
      bookImage: '/home/itinerary/ie-ireland/pattern.svg',
      landscapeImage: '/home/itinerary/ie-ireland/pattern.svg',
      title: '愛爾蘭',
      subtitle: 'Ireland',
      description: '愛爾蘭位在歐洲西北部，東臨愛爾蘭海與英國相望，大家稱之為翡翠之島。',
      linkText: null,
      linkUrl: null,
      order: 5,
      createdAt: '2025-08-28T13:03:41.930Z',
      updatedAt: '2025-08-28T13:03:41.930Z',
      groupProducts: [],
      freeProducts: [],
      recoProducts: [],
    },
    {
      id: '68b053ba564da72a7ab1753b',
      bookImage: '/home/itinerary/de-germany/pattern.svg',
      landscapeImage: '/home/itinerary/de-germany/pattern.svg',
      title: '德國',
      subtitle: 'Germany',
      description: '德國位於中歐的心臟地帶，融合了豐富的歷史、現代的城市和美麗的自然景觀。',
      linkText: null,
      linkUrl: null,
      order: 6,
      createdAt: '2025-08-28T13:03:54.312Z',
      updatedAt: '2025-08-28T13:03:54.312Z',
      groupProducts: [],
      freeProducts: [],
      recoProducts: [],
    },
    {
      id: '68b053c6564da72a7ab1753c',
      bookImage: '/home/itinerary/hu-hungary/pattern.svg',
      landscapeImage: '/home/itinerary/hu-hungary/pattern.svg',
      title: '匈牙利',
      subtitle: 'Hungary',
      description: null,
      linkText: null,
      linkUrl: null,
      order: 7,
      createdAt: '2025-08-28T13:04:06.694Z',
      updatedAt: '2025-08-28T13:04:06.694Z',
      groupProducts: [],
      freeProducts: [],
      recoProducts: [],
    },
    {
      id: '68b053d4564da72a7ab1753d',
      bookImage: '/home/itinerary/es-spain/pattern.svg',
      landscapeImage: '/home/itinerary/es-spain/pattern.svg',
      title: '西班牙',
      subtitle: 'Spain',
      description: null,
      linkText: null,
      linkUrl: null,
      order: 8,
      createdAt: '2025-08-28T13:04:20.726Z',
      updatedAt: '2025-08-28T13:04:20.726Z',
      groupProducts: [],
      freeProducts: [],
      recoProducts: [],
    },
    {
      id: '68b053e0564da72a7ab1753e',
      bookImage: '/home/itinerary/gr-greece/pattern.svg',
      landscapeImage: '/home/itinerary/gr-greece/pattern.svg',
      title: '希臘',
      subtitle: 'Greece',
      description: null,
      linkText: null,
      linkUrl: null,
      order: 9,
      createdAt: '2025-08-28T13:04:32.030Z',
      updatedAt: '2025-08-28T13:04:32.030Z',
      groupProducts: [],
      freeProducts: [],
      recoProducts: [],
    },
    {
      id: '68b053f0564da72a7ab1753f',
      bookImage: '/home/itinerary/be-belgium/pattern.svg',
      landscapeImage: '/home/itinerary/be-belgium/pattern.svg',
      title: '比利時',
      subtitle: 'Belgium',
      description: null,
      linkText: null,
      linkUrl: null,
      order: 10,
      createdAt: '2025-08-28T13:04:48.257Z',
      updatedAt: '2025-08-28T13:04:48.257Z',
      groupProducts: [],
      freeProducts: [],
      recoProducts: [],
    },
  ],
  pagination: {
    page: 1,
    pageSize: 10,
    total: 10,
    pageCount: 1,
  },
}

export const useBooks = (): TUseHomeQueryResult<TBooks[], TBooksResponse> => {
  const query = useQuery<TBooks[], AxiosError<TApiResponse<TBooks[]>>>({
    queryKey: ['books'],
    queryFn: fetchBooksData,
  })

  return { query, mock: booksApiMock }
}
